### PR TITLE
Fixing state machine docs

### PR DESCRIPTION
**Pull request by brotherdetjr**
Is commit.release() an artifact of previous api version?

### CODE REVIEW

**Comment by jhalterman** [comment]
Release is still a valid operation and appropriate for the scenarios described in the docs. Are you not seeing it visible in the `Commit` class?

**Comment by brotherdetjr** [comment]
Hmm... pretty strange.
No, I don't see it in Commit class.
The package seems correct: io.atomix.copycat.server
And yes, I see release() in https://github.com/atomix/copycat/blob/master/server/src/main/java/io/atomix/copycat/server/Commit.java

I'm using io.atomix.copycat:copycat-server:1.0.0-rc2 and the IDEA shows Commit does not have release() method. Also Commit class from 1.0.0-rc2 does not extend ReferenceCounted<Commit<T>>, but AutoClosable.

Any Ideas?

**Comment by jhalterman** [comment]
I think it was just recently added. Try one of the newer RCs, like rc6 :)

**Comment by kuujo** [comment]
`Commit` extends `ReferenceCounted` in rc6. This doesn't break any APIs (`ReferenceCounted` is `AutoCloseable`) but is now the preferred method for releasing commits from the state machine as it is consistent with new terminology.

**Comment by kuujo** [comment]
Actually, on second thought I do think the `command()` getter is still not correct. I removed that before releasing it IIRC

**Comment by brotherdetjr** [comment]
Thanks for the clarification.
Ok, then I'll fix the typos that are still left at this page.
BTW, I took RC2 from http://atomix.io/copycat/docs/getting-started/ - another candidate for small fix :)

**Pull request closed without merging**
